<?php if ( ! defined('BASEPATH')) exit('No direct script access allowed'); 

class Issuu {

	public function md5_generator($url_vars,$secret_key) 
	{
        	// MD5 hash is generated by this Syntax
        	// SECRETbar2baz3foo1 <-- secred key and concatenated variables in ascending order
        	// see docs:  http://issuu.com/services/api/signingrequests.html
        	$md5_in         =       trim($secret_key);
        	ksort($url_vars); // key value pair must be sorts ASC by key, for MD5 hash generation
        	foreach ($url_vars as $key => $val) {
                	$md5_in .=      $key.$val;
        	}
        	$md5_out        =       md5($md5_in);
        	return $md5_out;
	}

	public function cgi_values_constructor($url_vars) 
	{
        	// just a build of CGI values, returns string of CGI values
        	ksort($url_vars);
        	$count = 0;
		$output = NULL;
		foreach ($url_vars as $key => $val) {
                	if ($count      ==      0) {
                        	$cgi_sep        =       '?';
                	} else {
                        	$cgi_sep        =       '&';
                	}
                	$output .=      $cgi_sep.$key.'='.$val;
                	$count++;
        	}
        	return $output;
	}

	public function url_call_generator($cgi_values,$md5_hash) 
	{
        	// final generation of request to send to issue for response    
        	$output =       'http://api.issuu.com/1_0';
        	$output .=      $cgi_values.'&signature='.$md5_hash;

        	return $output;
	}

	public function feedurl($mediasource,$folderid)
	{
		$CI =& get_instance();
		$CI->load->library('Pubconfig');
		$credentials = $CI->pubconfig->apiCreds($mediasource); 
		$api_key = $credentials['apikey'];
		$api_sec = $credentials['apisecret'];

		$url_vars       =       array(
                	'startIndex'            =>      '0',
                	'folderId'              =>      $folderid,
                	'format'                =>      'xml',
                	'action'                =>      'issuu.bookmarks.list',
                	'apiKey'                =>      $api_key,
                	'pageSize'              =>      '30',
                	'bookmarkSortBy'        =>      'created',
                	'resultOrder'           =>      'desc'
        	);
		$feedURL        =       $this->url_call_generator($this->cgi_values_constructor($url_vars),$this->md5_generator($url_vars,$api_sec));
		// print_r($feedURL);
		return $feedURL;
	}

	public function findFolders($mediasource)
	{
		$CI =& get_instance();
		$CI->load->library('Pubconfig');
		$credentials = $CI->pubconfig->apiCreds($mediasource); 
		$api_key = $credentials['apikey'];
		$api_sec = $credentials['apisecret'];

		$url_vars       =       array(
                	'startIndex'            =>      '0',
                	'format'                =>      'xml',
                	'action'                =>      'issuu.folders.list',
                	'apiKey'                =>      $api_key,
                	'pageSize'              =>      '30',
                	'folderSortBy'        	=>      'folderId',
                	'resultOrder'           =>      'desc'
        	);
		$folders        =       $this->url_call_generator($this->cgi_values_constructor($url_vars),$this->md5_generator($url_vars,$api_sec));
		// print_r($feedURL);
		return $folders;
	}
	
}

/* End of file Issuu.php */
